#!/usr/bin/env bash
# Packs the extension into a signed .crx and regenerates the update manifest.
#
# Usage: tools/build-crx.sh [path/to/signing-key.pem]
#
# The signing key is NOT in this repo and must never be committed — whoever
# holds it controls updates to every installed copy. Keep it in the team
# password manager and pass its path here (default: ./van-enhancement-suite.pem).
#
# Chrome's packer archives the entire directory it is given, so we stage only
# the files the extension actually ships — not tools/, the source CSV, or .git.

set -euo pipefail

cd "$(dirname "$0")/.."

KEY="${1:-van-enhancement-suite.pem}"
CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
REPO="pacc2026/van-enhancement-suite"
UPDATE_BASE="https://pacc2026.github.io/van-enhancement-suite"

[ -f "$KEY" ] || { echo "No signing key at: $KEY" >&2; exit 1; }
[ -x "$CHROME" ] || { echo "Chrome not found at: $CHROME" >&2; exit 1; }

VERSION=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' manifest.json | head -1)
[ -n "$VERSION" ] || { echo "Could not read version from manifest.json" >&2; exit 1; }

# --- stage only what ships -------------------------------------------------
# Clean only this script's own outputs: build/ also holds the Firefox .xpi
# from tools/build-xpi.sh, and the two builds can run in either order.
STAGE=build/van-enhancement-suite
CRX="build/van-enhancement-suite-${VERSION}.crx"
rm -rf "$STAGE" build/van-enhancement-suite.crx "$CRX"
mkdir -p "$STAGE"
cp manifest.json "$STAGE/"
cp -R src "$STAGE/"
find "$STAGE" -name '.DS_Store' -delete

# --- pack ------------------------------------------------------------------
# Chrome writes <stage>.crx beside the staged directory. It exits non-zero on
# some builds despite succeeding, so check for the artifact rather than $?.
"$CHROME" --pack-extension="$PWD/$STAGE" --pack-extension-key="$PWD/$KEY" \
  --no-message-box >/dev/null 2>&1 || true

[ -f "build/van-enhancement-suite.crx" ] || { echo "Packing failed: no .crx produced" >&2; exit 1; }

mv build/van-enhancement-suite.crx "$CRX"
rm -rf "$STAGE"

# --- extension ID ----------------------------------------------------------
# First 128 bits of SHA256(DER public key), with hex digits remapped to a-p.
EXT_ID=$(openssl rsa -in "$KEY" -pubout -outform DER 2>/dev/null \
  | openssl dgst -sha256 -binary | xxd -p -c32 | cut -c1-32 | tr '0-9a-f' 'a-p')

# --- update manifest -------------------------------------------------------
# Chrome polls this XML and compares its version to the installed one, then
# downloads `codebase` if it is newer. Served from GitHub Pages over HTTPS;
# the .crx itself rides on the matching GitHub release.
mkdir -p docs
cat > docs/updates.xml <<XML
<?xml version='1.0' encoding='UTF-8'?>
<!-- GENERATED by tools/build-crx.sh — do not edit by hand. -->
<gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
  <app appid='${EXT_ID}'>
    <updatecheck codebase='https://github.com/${REPO}/releases/download/v${VERSION}/van-enhancement-suite-${VERSION}.crx'
                 version='${VERSION}' />
  </app>
</gupdate>
XML

echo "version:      $VERSION"
echo "extension ID: $EXT_ID"
echo "crx:          $CRX ($(wc -c <"$CRX" | tr -d ' ') bytes)"
echo "update xml:   docs/updates.xml  ->  $UPDATE_BASE/updates.xml"
echo
echo "Next: gh release create v$VERSION $CRX --title \"v$VERSION\" --notes \"...\""
echo "      then commit docs/updates.xml so Chrome sees the new version."
